# Generated by Django 3.0.7 on 2020-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date of Appointment', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AppointMents',
        ),
    ]
