# Generated by Django 3.0.7 on 2020-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0005_auto_20200627_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorName',
            field=models.CharField(default='doctor 1', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorPhoto',
            field=models.CharField(default='patient 1', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientPhoto',
            field=models.CharField(default='patient 1', max_length=100),
        ),
    ]
