# Generated by Django 3.0.7 on 2020-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0006_auto_20200627_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='special',
            field=models.EmailField(default='ortho', max_length=100),
        ),
    ]
