# Generated by Django 3.0.7 on 2020-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0007_appointment_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='special',
            field=models.CharField(default='ortho', max_length=100),
        ),
    ]
