# Generated by Django 3.0.7 on 2020-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0009_auto_20200627_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Not Reviewed'), ('Accepted', 'Accept'), ('Declined', 'Reject')], default='Unreviewed', max_length=20),
        ),
    ]
