# Generated by Django 3.0.7 on 2020-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='User Surname', max_length=50),
        ),
    ]
