# Generated by Django 3.0.7 on 2020-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
