# Generated by Django 3.0.7 on 2020-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200628_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bgroup',
            field=models.CharField(default='', max_length=200),
        ),
    ]
